// src/pages/react1/App.jsx
import React, { useEffect, useState } from "react";
import { getSchema } from "../../utils";
import BaseInfo from "./components/BaseInfo";
import Exps from "./components/Exps";
import OtherInfo from "./components/OtherInfo";
import "./index.scss";

export default function App() {
  const [data, setJSON] = useState(getSchema());
  useEffect(() => {
    window.refresh = () => {
      setJSON(getSchema());
    };
  }, []);
  const { name, position, infos = [], leftExps = [], rightExps = [] } = data;
  return (
    <div>
      <header>
        <BaseInfo name={name} position={position} />
        <OtherInfo infos={infos} />
      </header>
      <div className="exps">
        <div className="left">
          <Exps exps={leftExps} />
        </div>
        <div className="right">
          <Exps exps={rightExps} />
        </div>
      </div>
    </div>
  );
}

// src/pages/vue1/App.vue
<template>
  <div>
    <header>
      <!-- 姓名 -->
      <h1>{{ data.name }}</h1>
      <!-- 职位 -->
      <h2>{{ data.position }}</h2>
      <!-- 基本信息 -->
      <Infos :infos="data.infos" />
    </header>
    <Exps :exps="data.exps" />
  </div>
</template>

<script>
import { getSchema } from "./../../utils/index";
import Exps from "./components/Exps.vue";
import Infos from "./components/Infos.vue";

export default {
  components: {
    Infos,
    Exps,
  },
  data() {
    return {
      data: getSchema(),
    };
  },
  mounted() {
    window.refresh = this.refresh;
  },
  methods: {
    refresh() {
      this.data = getSchema();
    },
  },
};
</script>
